import { Link } from 'react-router-dom'

export function PrivacyPage() {
  return (
    <article className="policy-page">
      <header>
        <p className="privacy-chip">Institutional policy</p>
        <h1>Privacy Policy</h1>
        <p className="lede">
          Agent 66 is a counselling-support routing system operated for{' '}
          <strong>[Institution Name]</strong>. This page explains how information
          is processed to connect students with authorised human support while
          protecting privacy.
        </p>
      </header>

      <section className="policy-section">
        <h2>Registration and account approval</h2>
        <p>
          Student registration requests are reviewed by an authorised
          administrator before an account is activated. Registration details such
          as name, student identifier, institutional email, username, branch, and
          year are processed for account provisioning and administrative review.
        </p>
        <p>
          After approval, Agent 66 may send credential email containing a
          temporary password. Temporary credentials must be changed once through
          the initial password-change workflow. Passwords are stored only as
          secure hashes.
        </p>
      </section>

      <section className="policy-section">
        <h2>Email communication</h2>
        <p>
          The system may send operational email for registration review notices
          and approved credential delivery. Email content is limited to necessary
          account administration information and does not include counselling
          session notes or authentication secrets beyond the temporary password
          delivered to the student.
        </p>
      </section>

      <section className="policy-section">
        <h2>Purpose of processing</h2>
        <p>
          Information submitted through Agent 66 is processed to recognise when a
          student may benefit from professional support, route requests to
          authorised personnel, coordinate appointments and follow-ups, manage
          academic accommodation notices where permitted, and maintain operational
          accountability through audit logging.
        </p>
      </section>

      <section className="policy-section">
        <h2>Registration information</h2>
        <p>
          Student registration requests may include name, student identifier,
          institutional email, username, branch or department, and year of study.
          Requests remain pending until an authorised administrator reviews them.
          Accounts are not activated automatically.
        </p>
      </section>

      <section className="policy-section">
        <h2>Admin approval and email communication</h2>
        <p>
          Administrators receive notification when a registration request is
          submitted. If a request is approved, the student may receive a
          credential email containing a temporary password generated by the
          server. Temporary credentials are intended only for initial sign-in and
          one-time password change.
        </p>
      </section>

      <section className="policy-section">
        <h2>Password security</h2>
        <p>
          Passwords are stored only as secure hashes. Temporary passwords are not
          retained in plaintext after delivery processing. After the required
          one-time password change, further changes through that workflow are
          blocked by the server.
        </p>
      </section>

      <section className="policy-section">
        <h2>Privacy and role-based access</h2>
        <p>
          Access within Agent 66 is role-based. Users only receive the functions
          and records their role is authorised to use. Frontend screens may hide
          navigation, but backend authorisation remains the authoritative control.
        </p>
        <ul>
          <li>Students may request support and view approved wellbeing resources.</li>
          <li>Counsellors may manage referrals, sessions, and restricted records.</li>
          <li>Mentors and faculty may refer students and view referral workflow information available to their role.</li>
          <li>Academic leadership roles may access aggregate reporting and audit metadata where authorised.</li>
        </ul>
      </section>

      <section className="policy-section">
        <h2>Restricted counselling records</h2>
        <p>
          Counselling session records are treated as confidential professional
          information. Access is restricted to authorised counselling roles, with
          limited student access only to a student&apos;s own record where the
          backend permits it. Mentors, faculty, and general academic users do not
          receive counselling session summaries through this system.
        </p>
      </section>

      <section className="policy-section">
        <h2>Encryption and audit logging</h2>
        <p>
          The platform is designed to store operational data in an encrypted
          institutional database and to record metadata-only audit events for
          significant actions. Audit logs are intended to capture who acted, what
          type of resource was accessed, when the action occurred, and the
          outcome — not counselling narrative content.
        </p>
      </section>

      <section className="policy-section">
        <h2>Crisis escalation</h2>
        <p>
          If a submitted message indicates a possible immediate safety risk, the
          system prioritises escalation to designated human authority and surfaces
          institution-approved emergency resources returned by the backend. Agent
          66 does not itself provide emergency medical or crisis counselling.
        </p>
      </section>

      <section className="policy-section">
        <h2>Academic accommodation privacy</h2>
        <p>
          Academic accommodation coordination is separated from counselling
          content. Academic contacts receive accommodation details required for
          educational arrangements, not the counselling reason or session notes.
        </p>
      </section>

      <section className="policy-section">
        <h2>Aggregate reporting</h2>
        <p>
          Authorised leadership roles may view anonymous aggregate statistics.
          Aggregate views are intended to support institutional planning without
          exposing personally identifiable counselling records.
        </p>
      </section>

      <section className="policy-section">
        <h2>Human oversight and limitations</h2>
        <p>
          Agent 66 supports recognition and routing. It does not diagnose, treat,
          or replace professional judgement. Final decisions about care,
          escalation, accommodations, and academic arrangements remain with
          authorised human professionals under institutional policy.
        </p>
      </section>

      <section className="policy-section">
        <h2>Contact</h2>
        <p>
          For privacy questions related to Agent 66, contact{' '}
          <strong>[Institution Privacy / Counselling Office Contact]</strong>.
          Retention schedules, legal officer details, and certification claims are
          maintained by the institution and are not asserted by this interface.
        </p>
      </section>

      <p className="policy-meta">
        <Link to="/login">Return to sign in</Link>
        {' · '}
        <Link to="/terms">Terms of Use</Link>
      </p>
    </article>
  )
}
